name: Python Setup

runs:
  using: composite
  steps:

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9.7"
        architecture: "x64"
        cache: "poetry"
        cache-dependency-path: |
          poetry.lock
          pyproject.toml

    - name: Install Python dependencies
      shell: bash
      run: |
        pip install poetry
        poetry install
