name: Heroku Deploy
on:
  workflow_call
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.7"
          architecture: "x64"
          cache: "poetry"
          cache-dependency-path: |
            poetry.lock
            pyproject.toml

      - name: Install Python dependencies
        run: |
          pip install poetry
          poetry install

      - name: Disable Debugging
        run: |
          poetry run python .github/workflows/utils/deploy_utils.py disable_debugging

      - name: Make migrations
        run: |
          poetry run python manage.py makemigrations
          poetry run python manage.py collectstatic --noinput

      - name: Run tests
        run: |
          poetry run python manage.py test

      - name: Export Dependencies
        run: poetry export -o requirements.txt --without-hashes

      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
