name: Heroku Deploy
on:
  workflow_call
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          architecture: "x64"

      - name: Install Python dependencies
        run: |
          pip3 install -r requirements.txt

      - name: Disable Debugging
        run: |
          python .github/workflows/deploy_utils.py disable_debugging

      - name: Make migrations
        run: |
          python manage.py makemigrations
          python manage.py collectstatic --noinput

      - name: Run tests
        run: |
          python manage.py test

      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
