name: Main Workflow
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:

  run-black:
    name: Run Black
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: ./.github/actions/python-setup

      - name: Lint python files
        if: success() || failure()
        run: poetry run black --check .

  run-pyright:
    name: Run Pyright
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: ./.github/actions/python-setup

      - name: Type Check Python Files
        if: success() || failure()
        run: poetry run pyright .

  django-tests:
    name: Django Tests
    runs-on: ubuntu-latest
    needs:
      - run-black
      - run-pyright

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: ./.github/actions/python-setup

      - name: Make migrations
        run: |
          poetry run python manage.py makemigrations
          poetry run python manage.py collectstatic --noinput

      - name: Run tests
        run: |
          poetry run python manage.py test

  heroku_deploy:
    name: Heroku Deploy
    needs: django-tests
    if: success() && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/heroku_deploy.yaml
    secrets: inherit
